module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    ADMIN_COLLECTION:'admin',
    CATEGORY_COLLECTION:'category',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    WHISH_COLLECTION:'whish',
    WALLET_COLLECTION:'wallet',
    PRODUCT_OFFERS:'productoffers',
    CATEGORY_OFFERS:'categoryoffers',
    COUPON_COLLECTION:'coupon'
}